apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ixtra-frontend
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 516915001847.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ixtra-frontend:3.4.5
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  namespace: ixtra-frontend
  name: ixtra-frontend-nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
